import { ICatalog } from '../../intefaces/interfaces';

export const CATALOG: ICatalog[] = [
  {
    id: '1',
    name: 'Apple iPhone 14 Pro Max',
    brand: 'Apple',
    category: 'Phones',
    description: 'Apple iOS, экран 6.7" OLED (1290x2796) 120 Гц, Apple A16 Bionic, ОЗУ 6 ГБ, флэш-память 1 ТБ, камера 48 Мп, аккумулятор 4323 мАч, влагозащита IP68',
    price: 2500,
    amount: '14',
    image: ['https://i.ibb.co/6RB3P5C/9a292a436e9ec71215536b404dbf5087.jpg',
      'https://i.ibb.co/T2Hvfst/3d484378cabf38ac60987e33a2fd5eb2.jpg'],
    rating: '4.90',
  },
  {
    id: '2',
    name: 'Apple iPhone 14 Plus',
    brand: 'Apple',
    category: 'Phones',
    description: 'Apple iOS, экран 6.7" OLED (1284x2778) 60 Гц, Apple A15 Bionic, ОЗУ 6 ГБ, флэш-память 512 ГБ, камера 12 Мп, 1 SIM, влагозащита IP68',
    price: 2400,
    amount: '18',
    image: ['https://i.ibb.co/MBz6fhD/apple-14-plus.jpg',
      'https://i.ibb.co/54xhMjS/apple-14-plus-2.jpg'],
    rating: '4.89',
  },
  {
    id: '3',
    name: 'Samsung Galaxy S22 5G',
    brand: 'Samsung',
    category: 'Phones',
    description: 'Android, экран 6.1" AMOLED (1080x2340) 120 Гц, Exynos 2200, ОЗУ 8 ГБ, флэш-память 128 ГБ, камера 50 Мп, аккумулятор 3700 мАч, 2 SIM, влагозащита IP68',
    price: 870,
    amount: '32',
    image: ['https://i.ibb.co/3hGCHpn/samsung-s22.jpg',
      'https://i.ibb.co/5x0Ss7Q/samsung-s22-2.jpg'],
    rating: '4.75',
  },
  {
    id: '4',
    name: 'Apple iPhone 11',
    brand: 'Apple',
    category: 'Phones',
    description: 'Apple iOS, экран 6.1" IPS (828x1792), Apple A13 Bionic, ОЗУ 4 ГБ, флэш-память 64 ГБ, камера 12 Мп, аккумулятор 3046 мАч, 1 SIM, влагозащита IP68',
    price: 700,
    amount: '11',
    image: ['https://i.ibb.co/6w7fWSS/apple-11.jpg',
      'https://i.ibb.co/vxqqs8h/apple-11-2.jpg'],
    rating: '4.91',
  },
  {
    id: '5',
    name: 'Samsung Galaxy S10',
    brand: 'Samsung',
    category: 'Phones',
    description: 'Android, экран 6.1" AMOLED (1440x3040), Exynos 9820, ОЗУ 8 ГБ, флэш-память 128 ГБ, карты памяти, камера 12 Мп, аккумулятор 3400 мАч, 2 SIM, влагозащита IP68',
    price: 580,
    amount: '14',
    image: ['https://i.ibb.co/yghBJ0G/samsung-s10.jpg',
      'https://i.ibb.co/z63WhBW/samsung-s10-2.jpg'],
    rating: '4.86',
  },
  {
    id: '6',
    name: 'Apple iPhone 13 Pro',
    brand: 'Apple',
    category: 'Phones',
    description: 'Apple iOS, экран 6.1" OLED (1170x2532) 120 Гц, Apple A15 Bionic, ОЗУ 6 ГБ, флэш-память 128 ГБ, камера 12 Мп, аккумулятор 3095 мАч, 1 SIM, влагозащита IP68',
    price: 1400,
    amount: '21',
    image: ['https://i.ibb.co/jLqRyby/apple-13-pro.jpg',
      'https://i.ibb.co/r4vd4DW/apple-13-pro-2.jpg'],
    rating: '4.93',
  },
  {
    id: '7',
    name: 'Samsung Galaxy Z Flip4',
    brand: 'Samsung',
    category: 'Phones',
    description: 'Android, экран 6.7" AMOLED (1080x2640) 120 Гц, Qualcomm Snapdragon 8+ Gen1, ОЗУ 8 ГБ, флэш-память 128 ГБ, камера 12 Мп, аккумулятор 3700 мАч, 1 SIM, влагозащита IPX8',
    price: 920,
    amount: '6',
    image: ['https://i.ibb.co/r0k19dS/samsung-z.jpg',
      'https://i.ibb.co/6X2qJk2/samsung-z-2.jpg'],
    rating: '4.89',
  },
  {
    id: '8',
    name: 'Xiaomi Mi Mix 4',
    brand: 'Xiaomi',
    category: 'Phones',
    description: 'Android, экран 6.67" AMOLED (1080x2400) 120 Гц, Qualcomm Snapdragon 888+, ОЗУ 12 ГБ, флэш-память 512 ГБ, камера 108 Мп, аккумулятор 4500 мАч, 2 SIM, влагозащита IP53',
    price: 1350,
    amount: '38',
    image: ['https://i.ibb.co/6ZRPXWM/xiaomi-mix.jpg',
      'https://i.ibb.co/RCZPpDv/xiaomi-mix-2.jpg'],
    rating: '4.71',
  },
  {
    id: '9',
    name: 'Xiaomi 12S Ultra',
    brand: 'Xiaomi',
    category: 'Phones',
    description: 'Android, экран 6.73" AMOLED (1440x3200) 120 Гц, Qualcomm Snapdragon 8+ Gen1, ОЗУ 12 ГБ, флэш-память 256 ГБ, камера 50.3 Мп, аккумулятор 4860 мАч, 2 SIM, влагозащита IP68',
    price: 1400,
    amount: '30',
    image: ['https://i.ibb.co/DL7y4K5/xiaomi-12s.jpg',
      'https://i.ibb.co/FgPhMwt/xiaomi-12s-2.jpg'],
    rating: '4.94',
  },
  {
    id: '10',
    name: 'Xiaomi Mi 11 Ultra',
    brand: 'Xiaomi',
    category: 'Phones',
    description: 'Android, экран 6.81" AMOLED (1440x3200) 120 Гц, Qualcomm Snapdragon 888, ОЗУ 12 ГБ, флэш-память 512 ГБ, камера 50 Мп, аккумулятор 5000 мАч, 2 SIM, влагозащита IP68',
    price: 1470,
    amount: '29',
    image: ['https://i.ibb.co/dLmMTCM/xiaomi-11.jpg',
      'https://i.ibb.co/hLBzjgb/xiaomi-11-2.jpg'],
    rating: '4.86',
  },
  {
    id: '11',
    name: 'Apple Macbook Air 13',
    brand: 'Apple',
    category: 'Laptop',
    description: '13.3" 2560 x 1600 IPS, 60 Гц, несенсорный, Apple M1 3200 МГц, 8 ГБ, SSD 256 ГБ, видеокарта встроенная, Mac OS, цвет крышки серый',
    price: 1360,
    amount: '17',
    image: ['https://i.ibb.co/bQvb76h/macbook-13.jpg',
      'https://i.ibb.co/zrrH5r4/macbook-13-2.jpg'],
    rating: '4.96',
  },
  {
    id: '12',
    name: 'Apple Macbook Pro 14',
    brand: 'Apple',
    category: 'Laptop',
    description: '14.2" 3024 x 1964 IPS, 120 Гц, несенсорный, Apple M1 Pro (8 ядер), 16 ГБ, SSD 512 ГБ, видеокарта встроенная, Mac OS, цвет крышки серебристый',
    price: 2700,
    amount: '11',
    image: ['https://i.ibb.co/HCRHJxj/macbook-14-2.jpg',
      'https://i.ibb.co/Jr28B4z/macbook-14.jpg'],
    rating: '4.99',
  },
  {
    id: '13',
    name: 'Apple Macbook Pro 16',
    brand: 'Apple',
    category: 'Laptop',
    description: '16.2" 3456 x 2234 IPS, 120 Гц, несенсорный, Apple M1 Max, 32 ГБ, SSD 1024 ГБ, видеокарта встроенная, Mac OS, цвет крышки серый',
    price: 5200,
    amount: '9',
    image: ['https://i.ibb.co/mFxm2Kd/macbook-16-2.jpg',
      'https://i.ibb.co/7NdVCFK/macbook-16.jpg'],
    rating: '4.90',
  },
  {
    id: '14',
    name: 'Xiaomi Notebook Pro 15',
    brand: 'Xiaomi',
    category: 'Laptop',
    description: '15.6" 3456 x 2160 OLED, 60 Гц, несенсорный, AMD Ryzen 5 5600H 3300 МГц, 16 ГБ DDR4, SSD 512 ГБ, видеокарта встроенная, цвет крышки серебристый',
    price: 1700,
    amount: '34',
    image: ['https://i.ibb.co/0sKJ45W/xiaomi-15.jpg',
      'https://i.ibb.co/4tZ6gHR/notebook-15-2.jpg'],
    rating: '4.73',
  },
  {
    id: '15',
    name: 'Xiaomi RedmiBook 14',
    brand: 'Xiaomi',
    category: 'Laptop',
    description: '14.0" 1920 x 1080 IPS, 60 Гц, несенсорный, Intel Core i3 8145U 2100 МГц, 8 ГБ DDR4, SSD 256 ГБ, видеокарта встроенная, цвет крышки серебристый',
    price: 870,
    amount: '39',
    image: ['https://i.ibb.co/ZLCqNQx/redmibook-14.jpg',
      'https://i.ibb.co/x5c1Vzd/redmibook-14-2.jpg'],
    rating: '4.83',
  },
  {
    id: '16',
    name: 'Xiaomi RedmiBook Pro 14',
    brand: 'Xiaomi',
    category: 'Laptop',
    description: '14.0" 2560 x 1600 IPS, 60 Гц, несенсорный, AMD Ryzen 7 5700U 1800 МГц, 16 ГБ DDR4, SSD 512 ГБ, видеокарта встроенная, цвет крышки серый',
    price: 1380,
    amount: '19',
    image: ['https://i.ibb.co/YLdySsW/redmibook-14-pro.jpg',
      'https://i.ibb.co/ySkLym4/redmibook-pro-14-2.jpg'],
    rating: '4.73',
  },
  {
    id: '17',
    name: 'Xiaomi Redmi G',
    brand: 'Xiaomi',
    category: 'Laptop',
    description: '16.1" 1920 x 1080 IPS, 60 Гц, несенсорный, Intel Core i5 10200H 2400 МГц, 16 ГБ DDR4, SSD 512 ГБ, видеокарта NVIDIA GeForce GTX 1650 4 ГБ GDDR5, цвет крышки черный',
    price: 1390,
    amount: '20',
    image: ['https://i.ibb.co/MMVNvfx/redmi-g.jpg',
      'https://i.ibb.co/NjFqzpN/redmi-g-2.jpg'],
    rating: '4.79',
  },
  {
    id: '18',
    name: 'Samsung Galaxy Book2',
    brand: 'Samsung',
    category: 'Laptop',
    description: '15.6" 1920 x 1080 OLED, 60 Гц, сенсорный, Intel Core i7 1165G7 2800 МГц, 16 ГБ LPDDR5, SSD 1024 ГБ, видеокарта встроенная, Windows 11, цвет крышки серебристый',
    price: 2400,
    amount: '5',
    image: ['https://i.ibb.co/k5qdZG1/samsung-book.jpg',
      'https://i.ibb.co/rZ0knNJ/samsung-book-2.jpg'],
    rating: '4.80',
  },
  {
    id: '19',
    name: 'Samsung Galaxy Book',
    brand: 'Samsung',
    category: 'Laptop',
    description: '15.6" 1920 x 1080 IPS, 60 Гц, несенсорный, Intel Core i5 1135G7 2400 МГц, 16 ГБ LPDDR4X, SSD 512 ГБ, видеокарта встроенная, Windows 10, цвет крышки серебристый',
    price: 1900,
    amount: '2',
    image: ['https://i.ibb.co/Trj0qKs/samsung-book-g.jpg',
      'https://i.ibb.co/MMX6nSf/samsung-book-g-2.jpg'],
    rating: '4.52',
  },
  {
    id: '20',
    name: 'Samsung Galaxy Ion',
    brand: 'Samsung',
    category: 'Laptop',
    description: '13.3" 1920 x 1080 IPS, 60 Гц, несенсорный, Intel Core i5 10210U 1600 МГц, 8 ГБ DDR4, SSD 256 ГБ, видеокарта встроенная, Windows 10, цвет крышки серебристый',
    price: 1400,
    amount: '1',
    image: ['https://i.ibb.co/f8BP3bM/samsung-ion.jpg',
      'https://i.ibb.co/McDtkQ1/samsung-ion-2.jpg'],
    rating: '4.80',
  },
  {
    id: '21',
    name: 'Apple Watch SE',
    brand: 'Apple',
    category: 'Accessories',
    description: 'умные часы, поддержка iOS, экран AMOLED 1.57" (324x394, сенсорный), шагомер, пульсометр, время работы: 18 часов, корпус: алюминий, браслет: фторэластомер',
    price: 380,
    amount: '48',
    image: ['https://i.ibb.co/XywPdcP/apple-watch-se.jpg',
      'https://i.ibb.co/swRkBqQ/apple-watch-se-2.jpg'],
    rating: '4.95',
  },
  {
    id: '22',
    name: 'Apple Watch Series 6',
    brand: 'Apple',
    category: 'Accessories',
    description: 'умные часы, поддержка iOS, экран AMOLED 1.78" (368x448, сенсорный), шагомер, пульсометр, время работы: 18 часов, корпус: алюминий, браслет: фторэластомер',
    price: 670,
    amount: '43',
    image: ['https://i.ibb.co/TkpHT5h/apple-watch-6.jpg',
      'https://i.ibb.co/mNyLBYs/apple-watch-6-2.jpg'],
    rating: '4.96',
  },
  {
    id: '23',
    name: 'Apple Watch Series 3',
    brand: 'Apple',
    category: 'Accessories',
    description: 'умные часы, поддержка iOS, экран AMOLED 1.65" (312x390, сенсорный), шагомер, пульсометр, время работы: 18 часов, корпус: алюминий, браслет: фторэластомер',
    price: 250,
    amount: '60',
    image: ['https://i.ibb.co/Gp4zXng/apple-watch-3.jpg',
      'https://i.ibb.co/8jL2bPs/apple-watch-3-2.jpg'],
    rating: '4.91',
  },
  {
    id: '24',
    name: 'Xiaomi Smart Band 7',
    brand: 'Xiaomi',
    category: 'Accessories',
    description: 'фитнес-браслет, поддержка Android/iOS, экран AMOLED 1.62" (192x490, сенсорный), шагомер, пульсометр, время работы: 2 недели, корпус: пластик, браслет: силикон',
    price: 47,
    amount: '89',
    image: ['https://i.ibb.co/RHMNbpg/mi-band-7.jpg',
      'https://i.ibb.co/n3xCMLC/mi-band-7-2.jpg'],
    rating: '4.93',
  },
  {
    id: '25',
    name: 'Xiaomi Mi Smart Band 6',
    brand: 'Xiaomi',
    category: 'Accessories',
    description: 'фитнес-браслет, поддержка Android/iOS, экран AMOLED 1.56" (152x486, сенсорный), шагомер, пульсометр, время работы: 2 недели, корпус: пластик, браслет: силикон',
    price: 34,
    amount: '42',
    image: ['https://i.ibb.co/hc5HQhs/mi-band-6.jpg',
      'https://i.ibb.co/FqcFzSd/mi-band-6-2.jpg'],
    rating: '4.73',
  },
  {
    id: '26',
    name: 'Xiaomi Mi Smart Band 5',
    brand: 'Xiaomi',
    category: 'Accessories',
    description: 'фитнес-браслет, поддержка Android/iOS, экран AMOLED 1.1" (126x294, сенсорный), шагомер, пульсометр, время работы: 2 недели 6 суток, корпус: пластик, браслет: силикон',
    price: 36,
    amount: '29',
    image: ['https://i.ibb.co/pvyYrb5/mi-band-5.jpg',
      'https://i.ibb.co/P534WX4/mi-band-5-2.jpg'],
    rating: '4.81',
  },
  {
    id: '27',
    name: 'Samsung Galaxy Watch4',
    brand: 'Samsung',
    category: 'Accessories',
    description: 'умные часы, поддержка Android, экран AMOLED 1.4" (450x450, сенсорный), шагомер, пульсометр, время работы: 1 сутки 16 часов, корпус: сталь, браслет: фторэластомер',
    price: 390,
    amount: '25',
    image: ['https://i.ibb.co/1nknhRw/samsung-watch4.jpg',
      'https://i.ibb.co/pfG4ssV/samsung-watch4-2.jpg'],
    rating: '4.70',
  },
  {
    id: '28',
    name: 'Samsung Galaxy Active2',
    brand: 'Samsung',
    category: 'Accessories',
    description: 'умные часы, поддержка Android/iOS, экран AMOLED 1.2" (360x360, сенсорный), шагомер, пульсометр, время работы: 3 суток 23 часа, корпус: алюминий, браслет: фторэластомер',
    price: 200,
    amount: '9',
    image: ['https://i.ibb.co/2k2rJV6/watch-active2.jpg',
      'https://i.ibb.co/L0NmBkv/watch-active2-2.jpg'],
    rating: '4.81',
  },
  {
    id: '29',
    name: 'Samsung Galaxy Watch3',
    brand: 'Samsung',
    category: 'Accessories',
    description: 'умные часы, поддержка Android/iOS, экран AMOLED 1.2" (360x360, сенсорный), шагомер, пульсометр, корпус: сталь, браслет: кожа',
    price: 290,
    amount: '10',
    image: ['https://i.ibb.co/xCZmtgL/watch3.jpg',
      'https://i.ibb.co/dmNGHrn/watch3-2.jpg'],
    rating: '4.84',
  },
  {
    id: '30',
    name: 'Samsung Galaxy Watch',
    brand: 'Samsung',
    category: 'Accessories',
    description: 'умные часы, поддержка Android/iOS, экран AMOLED 1.2" (360x360, сенсорный), шагомер, пульсометр, время работы: 5 суток, корпус: сталь, браслет: силикон',
    price: 360,
    amount: '1',
    image: ['https://i.ibb.co/pjvC6Wj/watch.jpg',
      'https://i.ibb.co/M6wf7tp/watch-2.jpg'],
    rating: '4.79',
  },
];